### ISSUE TITLE
Kube Object Type Sequencer

### ISSUE THREAD

**Issue by hatfieldbrian** [RamenDR/ShioRamen#12]
Function: Orders Kube object capture and recovery
Inputs: Type capture order, type recovery order

## Type matching precedence (a.k.a. order of operations):
1. No duplicate type entries allowed.  Object update/create fails using API server admission controller to require unique values
1. full matches (non-star, non-not)
1. substring matches (star(s) concatenated with something) from top to bottom in a greedy fashion
1. catch-all (star concatenated with nothing)

## Notes
- There may be overlapping types with wildcards, expansion to an empty set it OK.

## Tasks:
- [x] Readme.md written with example inputs and outputs/behavior - sprint 2
- [x] VRG API: protect and recover order slices of type names - sprint 2
- [x] function for backup (a.k.a. capture); completion criteria: compiles, passes functional test - sprint 2
- [x] function for restore - sprint 3
-  ~~Protection e2e test(s) without wildcards (*), without nots (!), type names only; completion criteria: tests written and passing  - sprint 4~~
- [x] Recovery e2e tests; completion criteria: tests written and passing - sprint 5
- ~~e2e test wildcard and not functionality - future sprint~~
