### ISSUE TITLE
CPD Demo pre-req: As a Ramen developer, I can access an OpenShift cluster with a Cloud Pak installed, so that I can test Ramen disaster recovery of that Cloud Pak to another OpenShift cluster

### ISSUE THREAD

**Issue by hatfieldbrian** [RamenDR/ShioRamen#20]
- [x] Install ShioRamen or Ramen - completed in sprint 1
- [x] Expose minio ip address/hostname external to cluster with https and self-signed certificate - sprint 2
- [x] Generate and install x509 certificates for accessing minio service - sprint 2
- [x] Test ShioRamen protection function - sprint 2
- [x] Test ShioRamen recovery (a.k.a. failover) - sprint 2
- [x] Install Cloud Pak for Data (service provider) ~~with Nathan Brophy's help~~ (e.g. on one of Cechu's clusters that he loaned us) - sprint 3
- [x] Choose a Cloud Pak for Data service to deploy (e.g. Db2); consider asking Andy Streit for a recommendation - sprint 3
- [x] Deploy a Cloud Pak for Data service (a.k.a. application); consider using a script provided by Andy Streit if he has one - sprint 3
- [x] Expose minio ip address/hostname external to cluster with https without changing Ramen code (by having Ramen read certificates from existing supported certificate storage location) / Generate and install x509 certificates for accessing minio service using builtin openshift cluster method - sprint 4
- [x] Test ShioRamen protection function for busybox sample app with on a single cluster ~~sync RBD mirroring~~ - sprint 6
- [x] Test ShioRamen recovery (a.k.a. failover) for busybox sample app on a single cluster ~~with sync RBD mirroring~~ - sprint 6
- [ ] Test ShioRamen protection function for busybox sample app with a two OpenShift cluster setup with a single stretched sync scale/Fusion cluster - ~sprint 8~
- [ ] Test ShioRamen failover function for busybox sample app with a two OpenShift cluster setup with a single stretched sync scale/Fusion cluster - ~sprint 8~
- [x] Deploy and Protect a WordPress instance
- [x] Recover a WordPress instance to the same cluster it was deploy to/protected - sprint 8
- [x] Protect a Cloud Pak service's (e.g. Watson Studio) Kube objects and volumes - sprint 8
- [x] Recover a Cloud Pak service's (e.g. Watson Studio) Kube objects and volumes to the same cluster - sprint 8
- [ ] Recover a Cloud Pak service's (e.g. Watson Studio) Kube objects and volumes to a different cluster
- [ ] Protect and Recover multiple Cloud Pak services' (e.g. Watson Studio, Watson Knowledge Catalog, db2 warehouse) Kube objects and volumes to a different cluster
- [x] Install a fresh instance of CPD so that Watson Studio can be installed without Watson Knowledge Catalog and db2 warehouse - sprint 9
- [x] Protect Watson Studio instance by itself - sprint 9
- [x] Recover Watson Studio instance to same cluster - sprint 9
- [x] Setup two OCP clusters with ODF MetroDR (research hardware) with ODF 4.10 - sprint 11
- [ ] Setup two OCP clusters with ODF MetroDR (research hardware) with ODF 4.11 and Ramen 4.12 - sprint 13
- [ ] Two cluster failover with ODF of busybox app - sprint 13
- [ ] Two cluster failover with ODF of wordpress app - sprint 13
- [ ] Two cluster failover with ODF of wordpress app video record for demo
- [ ] Two cluster failover with ODF of cloud pak for data foundation layer
- [ ] Two cluster failover with ODF of cloud pak for data (watson studio)
- [ ] Two cluster failback with ODF of cloud pak for data (watson studio)
- [ ] Two cluster failback (warm standby) with ODF of cloud pak for data foundation layer (including final sync)
- [ ] Two cluster failover and failback with ODF of cloud pak for data (db2 warehouse)
- [ ] Two cluster failover and failback with ODF of cloud pak for data (watson knowledge catalog)

**Comment by hatfieldbrian** [comment]
Lisa has completed CPD 2-cluster failover and failback testing including repeatability 40x with Watson Studio, Watson Knowledge Catalog, and DB2 and reported in June 28th Fusion executive meeting.
