### ISSUE TITLE
Support Velero v1.9.0 API changes: multiple label selectors, restore merge option, restore status option, backup failure status logging - sprint 10

### ISSUE THREAD

**Issue by hatfieldbrian** [RamenDR/ShioRamen#58]
# Background
ShioRamen currently requires Velero version [1.8.1](https://github.com/vmware-tanzu/velero/releases/tag/v1.8.1) which was released March 14.  Version [1.9.0](https://github.com/vmware-tanzu/velero/releases/tag/v1.9.0) was released June 23.  It includes some API changes:
- An option to OR multiple label selectors; previously only one label selector was supported
- An option to merge changes into existing objects instead of not restoring them and warning
- An option to restore status for a set of resources; previously status was not restorable
- Backup failure reason stored in status; previously it was only available in the backup store and logs
- Status is part of each Velero resource and no longer a subresource

# Tasks
- [x] Require Velero version 1.9.0 by modifying `go.mod`.  Update the CRDs in `hack/test`.
- [x] Support the 3 new spec fields.  ShioRamen passes fields through to Velero so supporting the new options should be trivial.  The spec fields besides are currently common to backup and restore, though backup name's field name differs.  The `orLabelSelectors` are common too.  The `existingResourcePolicy` and `restoreStatus` are unique to restore.
- [x] Log the backup failure reason so that failures are easier to diagnose without examining velero logs.

**Comment by hatfieldbrian** [comment]
Fixed by https://github.com/RamenDR/ramen/pull/568

**Comment by hatfieldbrian** [comment]
Merged in ramendr/ramen#605
